# Generated by Django 6.0.4 on 2026-05-07 03:47

from django.db import migrations


def _table_exists(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)
    return table_name in tables


def _column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return {column.name for column in description}


def recreate_certificaterequest_if_needed(apps, schema_editor):
    table_name = "certificates_certificaterequest"

    expected_columns = {
        "id",
        "recipient_name",
        "recipient_email",
        "recipient_contact",
        "request_data",
        "status",
        "reviewed_date",
        "rejection_reason",
        "created_date",
        "updated_date",
        "generated_certificate_id",
        "requester_id",
        "reviewed_by_id",
        "template_id",
    }

    if _table_exists(schema_editor, table_name):
        current_columns = _column_names(schema_editor, table_name)
        if expected_columns.issubset(current_columns):
            return
        schema_editor.execute(f"DROP TABLE {table_name};")

    schema_editor.execute(
        """
        CREATE TABLE certificates_certificaterequest (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            recipient_name VARCHAR(300) NOT NULL,
            recipient_email VARCHAR(254),
            recipient_contact VARCHAR(20),
            request_data TEXT NOT NULL,
            status VARCHAR(20) NOT NULL,
            reviewed_date DATETIME,
            rejection_reason TEXT,
            created_date DATETIME NOT NULL,
            updated_date DATETIME NOT NULL,
            generated_certificate_id BIGINT UNIQUE,
            requester_id BIGINT NOT NULL REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED,
            reviewed_by_id BIGINT REFERENCES accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED,
            template_id BIGINT NOT NULL REFERENCES certificates_certificatetemplate(id) DEFERRABLE INITIALLY DEFERRED
        );
        """
    )
    schema_editor.execute(
        "CREATE INDEX certificates_certificaterequest_requester_id_idx ON certificates_certificaterequest (requester_id);"
    )
    schema_editor.execute(
        "CREATE INDEX certificates_certificaterequest_reviewed_by_id_idx ON certificates_certificaterequest (reviewed_by_id);"
    )
    schema_editor.execute(
        "CREATE INDEX certificates_certificaterequest_template_id_idx ON certificates_certificaterequest (template_id);"
    )
    schema_editor.execute(
        "CREATE INDEX certificates_certificaterequest_generated_certificate_id_idx ON certificates_certificaterequest (generated_certificate_id);"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificaterequest'),
    ]

    operations = [
        migrations.RunPython(recreate_certificaterequest_if_needed, migrations.RunPython.noop),
    ]
