# Generated by Django 6.0.4 on 2026-05-07 03:46

from django.db import migrations


def _table_exists(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)
    return table_name in tables


def _column_names(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    return {column.name for column in description}


def fix_certificaterequest_schema(apps, schema_editor):
    table_name = "certificates_certificaterequest"

    if not _table_exists(schema_editor, table_name):
        return

    columns = _column_names(schema_editor, table_name)

    # Fresh databases created by 0006 already have the desired schema.
    if {
        "recipient_name",
        "recipient_email",
        "recipient_contact",
        "requester_id",
        "reviewed_by_id",
        "reviewed_date",
    }.issubset(columns):
        return

    statements = []

    if "recipient_name" not in columns:
        statements.append(
            "ALTER TABLE certificates_certificaterequest ADD COLUMN recipient_name VARCHAR(300) NOT NULL DEFAULT '';"
        )
    if "recipient_email" not in columns:
        statements.append(
            "ALTER TABLE certificates_certificaterequest ADD COLUMN recipient_email VARCHAR(254) DEFAULT NULL;"
        )
    if "recipient_contact" not in columns:
        statements.append(
            "ALTER TABLE certificates_certificaterequest ADD COLUMN recipient_contact VARCHAR(20) DEFAULT NULL;"
        )

    if "requested_by_id" in columns and "requester_id" not in columns:
        statements.append(
            "ALTER TABLE certificates_certificaterequest RENAME COLUMN requested_by_id TO requester_id;"
        )
    if "processed_by_id" in columns and "reviewed_by_id" not in columns:
        statements.append(
            "ALTER TABLE certificates_certificaterequest RENAME COLUMN processed_by_id TO reviewed_by_id;"
        )
    if "processed_date" in columns and "reviewed_date" not in columns:
        statements.append(
            "ALTER TABLE certificates_certificaterequest RENAME COLUMN processed_date TO reviewed_date;"
        )

    for statement in statements:
        schema_editor.execute(statement)


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificaterequest'),
    ]

    operations = [
        migrations.RunPython(fix_certificaterequest_schema, migrations.RunPython.noop),
    ]
